deltree /y "MP3 NaviGatoR"
md "MP3 NaviGatoR"
copy mp3nav.exe "MP3 NaviGatoR"
copy mp3nav.ini "MP3 NaviGatoR"
copy mp3nav.q1  "MP3 NaviGatoR"
copy subst.ini  "MP3 NaviGatoR"
copy mp3nav.exe "MP3 NaviGatoR"
md "MP3 NaviGatoR\PlugIns"
copy PlugIns\in_mp3.dll "MP3 NaviGatoR\PlugIns"
copy PlugIns\out_ds.dll "MP3 NaviGatoR\PlugIns"
copy PlugIns\out_wave.dll "MP3 NaviGatoR\PlugIns"
md "MP3 NaviGatoR\Skins"
copy Skins\mainskin.bmp "MP3 NaviGatoR\Skins"
copy Skins\eqmain.bmp "MP3 NaviGatoR\Skins"
copy Skins\text.bmp "MP3 NaviGatoR\Skins"
del !mp3nav*.exe
start winrar a -sfx !mp3navigator_sfx.exe "MP3 NaviGatoR"
