// Do not edit. This file is machine generated by the Resource DLL Wizard.

library MP3NAV;

{$R *.RES}
{ITE} {LCID:00000419:00000419} {}
{ITE} {DFMFileType} {About.dfm}
{ITE} {DFMFileType} {DelEQPrUnit.dfm}
{ITE} {DFMFileType} {edUnit.dfm}
{ITE} {DFMFileType} {EQPrUnit.dfm}
{ITE} {DFMFileType} {EQUnit.dfm}
{ITE} {DFMFileType} {gEdUnit.dfm}
{ITE} {DFMFileType} {Main.dfm}
{ITE} {DFMFileType} {MaskAsk.dfm}
{ITE} {DFMFileType} {MaskHlpUnit.dfm}
{ITE} {DFMFileType} {Options.dfm}
{ITE} {DFMFileType} {ReqLyrUnit.dfm}
{ITE} {DFMFileType} {SaveEQPrUnit.dfm}
{ITE} {DFMFileType} {SrchUnit.dfm}
{ITE} {DFMFileType} {StatUnit.dfm}
{ITE} {DFMFileType} {uProgres.dfm}
{ITE} {DFMFileType} {vcl\DBLOGDLG.dfm}
{ITE} {DFMFileType} {vcl\DBPWDLG.dfm}
{ITE} {RCFileType} {MP3NAV_DRC.rc}

{$R 'About.dfm' AboutBox:TForm}
{$R 'DelEQPrUnit.dfm' DelEQPrForm:TForm}
{$R 'edUnit.dfm' edForm:TForm}
{$R 'EQPrUnit.dfm' EQPrForm:TForm}
{$R 'EQUnit.dfm' EQForm:TForm}
{$R 'gEdUnit.dfm' gEdForm:TForm}
{$R 'Main.dfm' MainForm:TForm}
{$R 'MaskAsk.dfm' MAskForm:TForm}
{$R 'MaskHlpUnit.dfm' MaskRulesForm:TForm}
{$R 'Options.dfm' OptionsForm:TForm}
{$R 'ReqLyrUnit.dfm' ReqLyrForm:TForm}
{$R 'SaveEQPrUnit.dfm' SaveEQPrForm:TForm}
{$R 'SrchUnit.dfm' QueryForm:TForm}
{$R 'StatUnit.dfm' StatusForm:TForm}
{$R 'uProgres.dfm' ProgressForm:TForm}
{$R 'vcl\DBLOGDLG.dfm' LoginDialog:TForm(Form)}
{$R 'vcl\DBPWDLG.dfm' PasswordDialog:TForm(Form)}
{$R 'MP3NAV_DRC.res' 'MP3NAV_DRC.rc'}

{$E rus}

begin
end.