Unit Quotes;

  Interface

const FCQuotes_Eng : array[0..40] of PChar = (
'You are not your job.',
'You are not how much you have in the bank.',
'You are not the contents of your wallet.',
'You are not your fucking Khakis.',
'You are not a beautiful and unique snowflake.',
'You are the all-singing, all-dancing crap of the world.',
'With insomnia, nothing is real. Everything is far away. Everything is a copy of a copy of a copy.',
'How much can you know about yourself if you''ve never been in a fight?',
'On a long enough timeline, the survival rate for everyone drops to zero.',
'When people think you''re dying, they listen, instead of waiting for their turn to speak.',
'With a gun in your mouth, you speak only in vowels.',
'The things you own end up owning you.',
'I wanted to put a bullet between the eyes of every panda that wouldn''t screw to save its species.',
'We are defined by the choices we make.',
'We were selling rich women their own fat asses back to them.',
'It''s only after you''ve lost everything that you''re free to do anything.',
'I say never be complete.',
'I say stop being perfect.',
'I say let''s evolve.',
'Let the chips fall where they may.',
'You are not special.',
'You are not a beautiful and unique snowflake.',
'You are the same decaying organic matter as everything else.',
'This is your life and it''s ending one minute at a time.',
'I wanted to destroy something beautiful.',
'With insomnia, you''re never really asleep; you''re never really awake.',
'Stop trying to control everything and just let go. LET GO !',
'You have a kind of sick desperation in your laugh.',
'Sticking feathers up your butt does not make you a chicken.',
'Tyler went away. Tyler''s gone.',
'I was living in a state of perpetual deja vu.',
'Is Mr. Durden building an army?',
'Our fathers were our models for God. If they bailed, what does that tell you about God? You have to be prepared for the possibility that God does not like you. In all probability, He hates you.',
'I wanna have your abortion.',
'I ran. I ran until my muscles burned and my veins pumped battery acid. Then I ran some more.',
'We''re not killing anyone, man, we''re setting them free !',
'If you wanna make an omlet you gotta break some eggs.',
'You created me. I didn''t create some loser alter-ego to make myself feel better.',
'You met me at a very strange time in my life.',
'I''d flip through catalogs and wonder, what kind of dining set defines me as a person?',
'Her lie reflected my lie.'
);

  implementation

end.